name: flutter_locafrog
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  flutter: 
    sdk: flutter
  font_awesome_flutter: ^9.2.0
  freezed_annotation: any
  dio: any
  flutter_secure_storage: any
  shared_preferences: any
  logger: ^1.1.0
  cupertino_icons: ^1.0.2
  auto_route: any
  youtube_player_flutter: 8.0.0
  get: 4.6.1
  html_character_entities:
  intl: ^0.17.0
  cached_network_image: ^3.2.0
  flutter_spinkit: ^5.1.0
  inview_notifier_list: ^3.0.0
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  google_sign_in: ^5.2.3
  cloud_firestore: ^3.1.6
  firebase_messaging: ^11.2.5
  flutter_dotenv: ^5.0.2

dev_dependencies: 
  auto_route_generator: any
  build_runner: any
  freezed: any
  json_serializable: any
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets: 
  - assets/json/
  - .env